
[tool.black]
line-length = 100

[tool.pytest.ini_options]
testpaths = "tests"
norecursedirs = ".git"
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
addopts = "-p syrupy --strict --cov=custom_components"
