#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if ! [ -x "$(which uv)" ]; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi

if ! [ -d ".venv" ]; then
  uv venv $VIRTUAL_ENV
  uv pip install -r requirements.test.txt
fi
