# Keep service names in sync with their respective name definitions in the const.py file.
bootstrap_blenders:

create_default_zone_schema:
  target:
    entity:
      domain: climate
      supported_features:
        - climate.ClimateEntityFeature.PRESET_MODE
  fields:
    schedule_id:
      required: true
      example: "schedule_1"
      default: "schedule_1"
      selector:
        select:
          translation_key: "schedule_id"
          options:
            - "schedule_1"
            - "schedule_2"
            - "schedule_3"
    weekday:
      required: true
      example: "mon"
      selector:
        select:
          translation_key: "weekday"
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"

dhw_auto_schedule:

force_system_rediscovery:

read_registers:
  fields:
    start_register:
      required: true
      example: 128
      selector:
        number:
          translation_key: "modbus_register"
          mode: box
    register_count:
      required: true
      example: 1
      default: 1
      selector:
        number:
          translation_key: "register_count"
          mode: box
          min: 1
          max: 10
    struct_format:
      required: true
      example: "=BB"
      default: "=H"
      selector:
        text:
          multiline: false
