name: coverage

on:
  workflow_run:
    workflows: [pytest]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        coverage_percent: ${{ steps.coverage_comment.outputs.coverage }}
        coverage_color: ${{ steps.coverage_comment.outputs.color }}

    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          merge-multiple: true
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Coverage comment
        id: coverage_comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ${{ github.workspace }}/pytest-coverage.txt
          title: Coverage report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: true
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          junitxml-path: ${{ github.workspace }}/junit-coverage.xml

  # Use a new job to create the badge, because if that fails, the coverage report
  # must still be available.
  coverage_badge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create the badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ff0da84bf72a3d20fb68db8cb9d3e38e
          filename: coverage_badge.json
          label: coverage
          message: "${{ needs.build.outputs.coverage_percent }}"
          color: ${{ needs.build.outputs.coverage_color }}