name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set PY env
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.test.txt
      - name: Run pytest
        run: |
          pytest --cov-report=term-missing --junitxml=${{ github.workspace }}/junit-coverage.xml --cov= tests/ | tee ${{ github.workspace}}/pytest-coverage.txt

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            ${{ github.workspace }}/junit-coverage.xml
            ${{ github.workspace }}/pytest-coverage.txt
          if-no-files-found: error
